---
apiVersion: v1
kind: Namespace
metadata:
  name: smee-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosmee
  namespace: smee-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosmee
  template:
    metadata:
      labels:
        app: gosmee
    spec:
      containers:
        - image: "ghcr.io/chmouel/gosmee:v0.26.0"
          imagePullPolicy: Always
          name: gosmee
          args: ["server", "--address", "0.0.0.0"]
          ports:
            - name: "gosmee-http"
              containerPort: 3333
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9100 # The sidecar's management port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 25 # Must be > the healthz handler's timeout
            failureThreshold: 2
        - name: gosmee-health-check-client
          image: ghcr.io/chmouel/gosmee:v0.26.0
          args:
            - client
            - http://localhost:3333/smeehealthcheckchannel
            - http://localhost:8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9100 # The sidecar's management port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 25 # Must be > the healthz handler's timeout
            failureThreshold: 2
          ports:
            - containerPort: 8081
              name: health
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 32Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: health-check-sidecar
          imagePullPolicy: Always
          image: quay.io/konflux-ci/smee-sidecar:latest
          env:
            # The sidecar checks the server on localhost
            - name: DOWNSTREAM_SERVICE_URL
              value: http://pipelines-as-code-controller.pipelines-as-code:8080
            - name: SMEE_CHANNEL_URL
              value: http://localhost:3333/smeehealthcheckchannel
            - name: HEALTHZ_TIMEOUT_SECONDS
              value: "10"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9100
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9100 # The sidecar's management port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 25 # Must be > the healthz handler's timeout
            failureThreshold: 2
