---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosmee-client
spec:
  template:
    spec:
      containers:
        - name: gosmee
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9100
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 25 # Must be > the healthz handler's timeout
            failureThreshold: 2
        - name: health-check-sidecar
          image: quay.io/konflux-ci/smee-sidecar:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9100
          # Patch this with the channel and the downstream service
          env:
          - name: DOWNSTREAM_SERVICE_URL
            value: "http://pipelines-as-code-controller.pipelines-as-code:8080"
          - name: SMEE_CHANNEL_URL
            value: "https://smee.io/abcdefg"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9100
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 25 # Must be > the healthz handler's timeout
            failureThreshold: 2
